# Generated by Django 3.0.8 on 2020-07-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost per Kg')),
                ('wages', models.IntegerField(default=0, verbose_name='wages per Kg')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name='date of salary updated')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Employee Name')),
                ('designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('address', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('dob', models.DateTimeField(verbose_name='date of birth')),
                ('doj', models.DateTimeField(verbose_name='date of Joined')),
                ('gender', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Salary')),
            ],
        ),
    ]
