# Generated by Django 3.0.8 on 2020-08-07 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Account Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Transaction Amount')),
                ('description', models.CharField(max_length=200, verbose_name='Transaction Description')),
                ('type', models.IntegerField(choices=[(0, 'Credit'), (1, 'Debit')], verbose_name='Credit/Debit')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date of Transaction')),
            ],
        ),
    ]
