# Generated by Django 3.0.8 on 2020-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=30, verbose_name='Supplier Name')),
                ('address', models.CharField(blank=True, default=' ', max_length=70)),
                ('phone', models.CharField(blank=True, default=' ', max_length=11, verbose_name='Phone Number')),
            ],
        ),
    ]
