# Generated by Django 3.0.8 on 2020-07-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='paid_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='product',
        ),
        migrations.AddField(
            model_name='employee',
            name='product',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='wages',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
