# Generated by Django 3.0.8 on 2020-08-18 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials_order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Of Buyed'),
        ),
        migrations.AddField(
            model_name='materials_order',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=30, verbose_name='User Name'),
        ),
    ]
