# Generated by Django 3.0.8 on 2020-07-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='NULL', max_length=30)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Employee')),
            ],
        ),
    ]
