# Generated by Django 3.0.8 on 2020-07-17 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200715_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='product',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='Not Found', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Nothing', max_length=30, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date of Joined'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (1, 'Others')], default=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='NULL', max_length=30, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0000000', max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='wages',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
