# Generated by Django 3.0.8 on 2020-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_accounts_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.BooleanField(verbose_name='Credit/Debit'),
        ),
    ]
