# Generated by Django 3.0.8 on 2020-07-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_work'),
        ('inventory', '0002_customer'),
    ]

    operations = [
    ]
