# Generated by Django 3.0.8 on 2020-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200717_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Manager', 'Manager'), ('Superviser', 'Superviser'), ('MarketingHead', 'MarketingHead'), ('Worker', 'others')], default='Others', max_length=200),
        ),
    ]
